import type { Transaction } from "../budgets/types";

export const CATEGORIES = [
  "Food",
  "Transportation",
  "Entertainment",
  "Utilities",
  "Healthcare",
  "Education",
  "Shopping",
  "Travel",
  "Personal Care",
  "Gifts & Donations",
];

export const TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    merchant: "Amazon",
    description: "Wireless keyboard and desk accessories",
    category: "Shopping",
    type: "expense",
    amount: 150,
    date: "2024-06-01",
  },
  {
    id: "2",
    merchant: "Starbucks",
    description: "Coffee and breakfast",
    category: "Food & Dining",
    type: "expense",
    amount: 12.75,
    date: "2024-06-02",
  },
  {
    id: "3",
    merchant: "Uber",
    description: "Airport ride",
    category: "Transportation",
    type: "expense",
    amount: 24.6,
    date: "2024-06-03",
  },
  {
    id: "4",
    merchant: "Netflix",
    description: "Monthly streaming subscription",
    category: "Entertainment",
    type: "expense",
    amount: 15.49,
    date: "2024-06-04",
  },
  {
    id: "5",
    merchant: "Walmart",
    description: "Weekly grocery run",
    category: "Groceries",
    type: "expense",
    amount: 86.32,
    date: "2024-06-05",
  },
  {
    id: "6",
    merchant: "Shell",
    description: "Fuel refill",
    category: "Fuel",
    type: "expense",
    amount: 52.1,
    date: "2024-06-06",
  },
  {
    id: "7",
    merchant: "Apple",
    description: "AirPods replacement",
    category: "Electronics",
    type: "expense",
    amount: 999,
    date: "2024-06-07",
  },
  {
    id: "8",
    merchant: "Target",
    description: "Home essentials and storage bins",
    category: "Shopping",
    type: "expense",
    amount: 64.29,
    date: "2024-06-08",
  },
  {
    id: "9",
    merchant: "Spotify",
    description: "Music premium plan",
    category: "Subscriptions",
    type: "expense",
    amount: 9.99,
    date: "2024-06-09",
  },
  {
    id: "10",
    merchant: "CVS",
    description: "Medicines and wellness items",
    category: "Health",
    type: "expense",
    amount: 21.45,
    date: "2024-06-10",
  },
  {
    id: "11",
    merchant: "Airbnb",
    description: "Weekend stay",
    category: "Travel",
    type: "expense",
    amount: 210,
    date: "2024-06-11",
  },
  {
    id: "12",
    merchant: "Acme Studio",
    description: "Freelance project payout",
    category: "Salary",
    type: "income",
    amount: 3200,
    date: "2024-06-12",
  },
];
